LANGUAGES = {
    "title": ["Lost & Found Pet System - All Reports", "Kayıp & Buluntu Hayvan Sistemi - Tüm İlanlar"],
    "report_details": ["Report Details", "İlan Ayrıntıları"],
    "new_report": ["New Report", "Yeni İlan"],
    "my_reports": ["My Reports", "Benim İlanlarım"],
    "all_reports": ["All Reports", "Tüm İlanlar"],
    "change_language": ["TR / EN", "EN / TR"],
    "profile": ["Profile", "Profil"],
    "edit_user": ["Edit User", "Kullanıcıyı Düzenle"],
    "delete_user": ["Delete User", "Kullanıcıyı Sil"],
    "delete_user_confirm": ["Are you sure you want to delete your account?", "Hesabınızı silmek istediğinizden emin misiniz?"],
    "user_deleted": ["User account deleted", "Kullanıcı hesabı silindi"],
    "success": ["Success", "Başarılı"],
    "error": ["Error", "Hata"],
    "no_image": ["No Image", "Resim Yok"],
    "pet_name": ["Pet Name", "Hayvan Adı"],
    "pet_type": ["Pet Type", "Hayvan Türü"],
    "location": ["Location", "Konum"],
    "description": ["Description", "Açıklama"],
    "photo": ["Photo", "Fotoğraf"],
    "browse": ["Browse", "Gözat"],
    "save": ["Save", "Kaydet"],
    "dog": ["Dog", "Köpek"],
    "cat": ["Cat", "Kedi"],
    "bird": ["Bird", "Kuş"],
    "other": ["Other", "Diğer"],
    "report_not_found": ["Report not found or is incomplete", "İlan bulunamadı veya eksik"],
    "image_not_found": ["Image file not found!", "Görüntü dosyası bulunamadı!"],
    "failed_to_load_image": ["Failed to load image", "Resim yüklenemedi"],
    "select_photo": ["Select Photo", "Fotoğraf Seç"],
    "image_files": ["Image Files", "Resim Dosyaları"],
    "failed_to_copy_photo": ["Failed to copy photo", "Fotoğraf kopyalanamadı"],
    "report_updated_successfully": ["Report updated successfully!", "İlan başarıyla güncellendi!"],
    "new_rep_title": ["New Report Page", "Yeni İlan Sayfası"],
    "photo_path": ["Photo Path", "Fotoğraf Yolu"],
    "save_report": ["Save Report", "İlanı Kaydet"],
    "all_fields_required": ["All fields are required!", "Tüm alanlar doldurulmalıdır!"],
    "report_saved": ["Report Saved", "İlan Kaydedildi"],
}
