LANGUAGES = {
    "titleAllReports": ["Lost & Found Pet System - All Reports", "Kayıp & Buluntu Hayvan Sistemi - Tüm İlanlar"],
    "report_details": ["Report Details", "İlan Ayrıntıları"],
    "new_report": ["New Report", "Yeni İlan"],
    "my_reports": ["My Reports", "Benim İlanlarım"],
    "all_reports": ["All Reports", "Tüm İlanlar"],
    "change_language": ["TR / EN", "EN / TR"],
    "profile": ["Profile", "Profil"],
    "edit_user": ["Edit User", "Kullanıcıyı Düzenle"],
    "delete_user": ["Delete User", "Kullanıcıyı Sil"],
    "delete_user_confirm": ["Are you sure you want to delete your account?", "Hesabınızı silmek istediğinizden emin misiniz?"],
    "user_deleted": ["User account deleted", "Kullanıcı hesabı silindi"],
    "success": ["Success", "Başarılı"],
    "error": ["Error", "Hata"],
    "no_image": ["No Image", "Resim Yok"],
    "pet_name": ["Pet Name :", "Hayvan Adı :"],
    "pet_type": ["Pet Type :", "Hayvan Türü :"],
    "location": ["Location :", "Konum :"],
    "description": ["Description", "Açıklama"],
    "photo": ["Photo", "Fotoğraf"],
    "browse": ["Browse", "Gözat"],
    "save": ["Save", "Kaydet"],
    "dog": ["Dog", "Köpek"],
    "cat": ["Cat", "Kedi"],
    "bird": ["Bird", "Kuş"],
    "other": ["Other", "Diğer"],
    "report_not_found": ["Report not found or is incomplete", "İlan bulunamadı veya eksik"],
    "image_not_found": ["Image file not found!", "Görüntü dosyası bulunamadı!"],
    "failed_to_load_image": ["Failed to load image", "Resim yüklenemedi"],
    "select_photo": ["Select Photo", "Fotoğraf Seç"],
    "image_files": ["Image Files", "Resim Dosyaları"],
    "failed_to_copy_photo": ["Failed to copy photo", "Fotoğraf kopyalanamadı"],
    "report_updated_successfully": ["Report updated successfully!", "İlan başarıyla güncellendi!"],
    "new_rep_title": ["New Report Page", "Yeni İlan Sayfası"],
    "photo_path": ["Photo Path", "Fotoğraf Yolu"],
    "save_report": ["Save Report", "İlanı Kaydet"],
    "all_fields_required": ["All fields are required!", "Tüm alanlar doldurulmalıdır!"],
    "report_saved": ["Report Saved", "İlan Kaydedildi"],
    "delete_report": ["Delete", "Sil"],
    "details_report": ["Details", "Detaylar"],
    "username": ["Username:", "Kullanıcı Adı:"],
    "password": ["Password:", "Şifre:"],
    "phoneNo": ["Phone Number:", "Telefon Numarası:"],
    "save": ["Save", "Kaydet"],
    "fillDataError": ["Please fill every user data before saving!", "Lütfen tüm bilgileri doldurun!"],
    "userUptaded": ["User updated successfully!", "Kullanıcı bilgilerini başarıyla güncellendi!"],
    "deleteTheReport": ["Delete Report", "Raporu Sil"],
    "imageNotFound": ["Image file not found!", "Fotoğraf bulunamadı!"],
    "failedImage": ["Failed to load image:", "Fotoğraf yüklenemedi:"],
    "passwordLength": ["Password length is not valid!(8-16)", "Şifre uzunluğu uygun değil!(8-16)"],
    "validPhone": ["Enter a valid phone number for Türkiye!", "Türkiye için uygun bir telefon numarası girin!"],
    "validPassword": ["Password is not valid!(There should be at least one capital letter, one letter and one digit. It shouldn't have any symbols.)", "Şifre uygun değil!(En az bir büyük harf, bir küçük harf ve bir sayı olmalı. Sembol içermemeli.)"],
    "usernameLength": ["Username length is not valid!(4-12)", "Kullanıcı adı uzuluğu uygun değil!(4-12)"],
    "validUsername": ["Username is not valid!(Symbols not allowed.)", "Kullanıcı adı uygun değil!(Sembol içermemeli.)"],
    "askDeleteReport": ["Are you sure you want to delete your report?", "Raporunu silmek istediğine emin misin?"],
    "askDeleteUser": ["Are you sure you want to delete your account?", "Hesabını silmek istediğine emin misin?"],
    "userDeleted": ["User account deleted.", "Hesap silindi."],
    "titleLogin": ["Lost & Found Pet System", "Kayıp & Buluntu Hayvan Sistemi"],
    "login": ["Login", "Giriş Yap"],
    "register": ["Register", "Kayıt Ol"],
    "warning": ["Warning", "Uyarı"],
    "welcome": ["Welcome, ", "Hoş geldin, "],
    "allfields": ["All fields are required!", "Tüm alanları doldurun!"],
    "usernameexists": ["Username already exists.", "Bu kullanıcı adı kullanılıyor."],
    "backtoLogin": ["Back to Login", "Giriş ekranına dön"],
    "registersuccess":["Registration successful!", "Kayıt olma başarılı!"],
    "invalidUsernameorPassword": ["Invalid username or password.", "Kullanıcı adı veya şifre yanlış."],
}

